language: python
python:
  - "2.7"
  - "3.4"
install:
- pip install coveralls
script: coverage run --source=. -m unittest discover -s tests/
notifications:
  email:
    recipients:
      - daikk115@gmail.com
    on_success: change
    on_failure: always
after_success:
- coveralls
